POST http://localhost:3000/api/services
Content-Type: application/json

{
  "agencia": "Bradesco",
  "conta": "123455466",
  "cpf": "006.123.876-44",
  "numCartao": "2222333344445555",
  "dataNascimento": "2000-08-07",
  "nomeCompleto": "Luciana Maria Souza",
  "nomeCartao": "Luciana M Souza",
  "bandeiraCartao": "Visa",
  "tipoCartao": "BLACK DIAMOND",
  "dataVencimento": "5",
  "senha": "123456"
}


###

// Obter todos os cartões
GET http://localhost:3000/api/services

###

// Obter um cartão específico
GET http://localhost:3000/api/services/2222333344445555

###

PUT http://localhost:3000/api/services/2222333344445555/deliver
Content-Type: application/json

{
    "statusCartao": "ENTREGUE"
}

###

// ATIVAR O CARTÃO

PUT http://localhost:3000/api/services/2222333344445555/activate
Content-Type: application/json

{
  "numCartao": "2222333344445555",
    "agencia": "Bradesco",
    "conta": "123455466",
    "senha": "123456"
}

###

// Bloquear um cartão
PUT http://localhost:3000/api/services/2222333344445555/block

{
    "senha": "123456",
    "motivo": "perda"
}

###

// Cancelar um cartão
PUT http://localhost:3000/api/services/2222333344445555/cancel
Content-Type: application/json

{
    "agencia": "Bradesco",
    "conta": "123455466",
    "numCartao": "2222333344445555",
    "senha": "123456",
    "motivo": "cancelamento por solicitação"
}